### ISSUE TITLE
Improve get_device_model

### ISSUE THREAD

**Issue by andpozo** [Chitrank-Dixit/django-fcm#13]
when app is installed, error is raised, we need add a fallback value for FCM_DEVICE_MODEL

**Comment by andpozo** [comment]
@Chitrank-Dixit can you review this issue?

**Comment by Chitrank-Dixit** [comment]
looked into the issue yes it is a better enhancement I also use in my django projects that way but didn't use in this one cheers. hope it resolves the issue
