### ISSUE TITLE
[Sugestion] This app should have DeviceAdmin?

### ISSUE THREAD

**Issue by Diegow3b** [Chitrank-Dixit/django-fcm#17]
in gcm one you have a admin called DeviceAdmin maybe fcm must have too?

**Comment by Chitrank-Dixit** [comment]
Yes if you are talking about the admin panel , we have added DeviceAdmin in the django admin panel , is this what you were asking ?

**Comment by Diegow3b** [comment]
I see, u have acceptec my pull request.
