### ISSUE TITLE
ImportError: cannot import name 'get_device_model'

### ISSUE THREAD

**Issue by pratikj009** [Chitrank-Dixit/django-fcm#21]
After adding the app to my django project, I got a import error:

File "/usr/local/lib/python3.5/dist-packages/fcm/forms.py", line 4, in <module>
    from .models import get_device_model
ImportError: cannot import name 'get_device_model'

It seems that you have moved the "get_device_model" function from models.py to utils.py and missed changing the import name in forms.py and admin.py

**Comment by ashish2py** [comment]
It seems it's a duplicate of #19. please import it from utils.py.

**Comment by ashish2py** [comment]
@pratikj009 I've already created a pull request for two bugs, wait for the update.

**Comment by pratikj009** [comment]
Thanks for the update @ashish2py

**Comment by saimzn4241** [comment]
this issue is solved now..good work @ashish2py ;
this issue must be closed now..
