### ISSUE TITLE
Bad inheritance

### ISSUE THREAD

**Issue by rmanganiello** [Chitrank-Dixit/django-fcm#35]
I don't understand why FCMMessage class inheritance from FCMMessage (with the same name) and reuse the super "send" method. Why don't you unify all the logic inside the same class with differents methods or rename base FCMMessage class?

https://github.com/Chitrank-Dixit/django-fcm/blob/master/fcm/utils.py#L99-L110

**Comment by Chitrank-Dixit** [comment]
updating this in the next coming release
