### ISSUE TITLE
relation "fcm_device" does not exist

### ISSUE THREAD

**Issue by mdamien** [Chitrank-Dixit/django-fcm#5]
When loading the admin, I get a classic error:

```
ProgrammingError at /admin/fcm/device/
relation "fcm_device" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "fcm_device"
```

I did run `./manage.py migrate` but looks like there's no `fcm_device` table.

**NOTE: To other people trying this package, I've had more success with [fcm-django](https://github.com/xtrinch/fcm-django)**

**Comment by Chitrank-Dixit** [comment]
after following all the installation instructions for django-fcm try running

`python manage.py makemigrations fcm`
then
`python manage.py migrate fcm`

then I think it would work.

**Comment by Chitrank-Dixit** [comment]
I hope it resolved your issue @mdamien if not you can contact me on my mail I would help you out.

**Comment by mdamien** [comment]
Hi, sorry but I switched to `fcm-django`, but #12 fixed it
