### ISSUE TITLE
Problem when customize Device model

### ISSUE THREAD

**Issue by andpozo** [Chitrank-Dixit/django-fcm#9]
When I define custom Device model in my settings, the Default device model is registered in the admin, may be should use a _swappable_ parameter in metaclass, like a User model in django

```python
class Device(AbstractDevice):
    pass
```

```python
class Device(AbstractDevice):
    class Meta:
        swappable = 'FCM_DEVICE_MODEL'
```

**Comment by andpozo** [comment]
@Chitrank-Dixit what you think about?

**Comment by Chitrank-Dixit** [comment]
Yes I have seen this and merged this, closing this issue
